name: noospherehub
networks:
  ns-network:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
services:
  noosphere-hub:
    image: ghcr.io/hpp-io/noosphere-hub:test2
    container_name: noosphere-hub
    user: '0:110'
    environment:
      - _JAVA_OPTIONS=-Xmx2048m -Xms1024m -Djava.net.preferIPv4Stack=true -Djavax.net.ssl.trustStore=/app/truststore.p12 -Djavax.net.ssl.trustStorePassword=${HPP_KEYSTORE_PASSWORD} -Dspring.cloud.consul.discovery.hostname=nstest.hpp.io -Dspring.cloud.consul.discovery.prefer-ip-address=false -Dspring.cloud.consul.discovery.scheme=https
      - SPRING_PROFILES_ACTIVE=test2,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:mysql://noosphere-mysql:3306/nshub?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
      - SPRING_LIQUIBASE_URL=jdbc:mysql://noosphere-mysql:3306/nshub?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://authtest.hpp.io/realms/noosphere
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=${HPP_AUTH_WEB_APP_SECRET}
      - SPRING_PULSAR_CLIENT_SERVICE_URL=pulsar://noosphere-pulsar:6650
      - SPRING_PULSAR_ADMINISTRATION_SERVICE_URL=http://noosphere-pulsar:9082
      - SPRING_CLOUD_CONSUL_HOST=noosphere-consul
      - APPLICATION_KEYCLOAK_AUTH_URL=https://authtest.hpp.io
      - APPLICATION_KEYCLOAK_ADMIN_CLIENT_SECRET=${HPP_AUTH_ADMIN_CLI_SECRET}
      - APPLICATION_KEYSTORE_STORE_PASSWORD=${HPP_KEYSTORE_PASSWORD}
      - APPLICATION_KEYSTORE_PATH=/app/hpp-keystore.p12
      - APPLICATION_KEYSTORE_KEYS_ETH=${HPP_ETH_KEY_ALIAS}
      - APPLICATION_BLOCKCHAIN_ROUTER_ADDRESS=${HPP_ROUTER_ADDRESS}
      - HPP_APP_KIT_PROJECT_ID=${HPP_APP_KIT_PROJECT_ID}
      - HPP_ENV=${HPP_ENV}
      - LOGGING_FILE_PATH=/app/logs
    volumes:
      - /data/noosphere/config/hpp-keystore.p12:/app/hpp-keystore.p12
      - /data/noosphere/config/truststore.p12:/app/truststore.p12
      - /data/noosphere/logs/nshub-logs:/app/logs
    ports:
      - 8085:8085
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - https://nstest.hpp.io/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    networks:
      - ns-network
  noosphere-gateway:
    image: ghcr.io/hpp-io/noosphere-gateway:test2
    container_name: noosphere-gateway
    user: '0:110'
    environment:
      - _JAVA_OPTIONS=-Xmx1024m -Xms512m -Djava.net.preferIPv4Stack=true -Djavax.net.ssl.trustStore=/app/truststore.p12 -Djavax.net.ssl.trustStorePassword=${HPP_KEYSTORE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=test2,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=noosphere-consul
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://authtest.hpp.io/realms/noosphere
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=${HPP_AUTH_WEB_APP_SECRET}
      - SPRING_PULSAR_CLIENT_SERVICE_URL=pulsar://noosphere-pulsar:6650
      - SPRING_PULSAR_ADMINISTRATION_SERVICE_URL=http://noosphere-pulsar:9082
      - APPLICATION_KEYCLOAK_AUTH_URL=https://authtest.hpp.io
      - APPLICATION_KEYCLOAK_ADMIN_CLIENT_SECRET=${HPP_AUTH_ADMIN_CLI_SECRET}
      - LOGGING_FILE_PATH=/app/logs
      - HPP_APP_KIT_PROJECT_ID=${HPP_APP_KIT_PROJECT_ID}
      - HPP_ENV=${HPP_ENV}
    volumes:
      - /data/noosphere/config/truststore.p12:/app/truststore.p12
      - /data/noosphere/logs/ng-logs:/app/logs
    ports:
      - 8280:8280
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - ns-network
  noosphere-auth:
    container_name: noosphere-auth
    user: '0:110'
    image: ghcr.io/hpp-io/noosphere-auth:test2-amd64
    command: 'start'
    volumes:
      - /data/noosphere/config/realm-config:/opt/keycloak/data/import
      - /data/noosphere/config/realm-config/keycloak-health-check.sh:/opt/keycloak/health-check.sh
    environment:
      - KC_DB_URL_HOST=noosphere-mysql
      - KC_DB_URL_PORT=3306
      - KC_DB_USERNAME=${DATABASE_USERNAME}
      - KC_DB_PASSWORD=${DATABASE_PASSWORD}
      - KC_DB=mysql
      - KC_PROXY=passthrough
      - KC_HOSTNAME=authtest.hpp.io
      - KC_HOSTNAME_URL=https://authtest.hpp.io
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_FEATURES=scripts
      - KC_HTTP_PORT=9080
      - KC_HEALTH_ENABLED=true
      - KC_HTTP_ENABLED=true
      - KC_HTTP_MANAGEMENT_PORT=9990
      - KC_HOSTNAME_STRICT=true
      - KC_HOSTNAME_STRICT_HTTPS=true
      - JDBC_PARAMS='useUnicode=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true'
      - JAVA_OPTS='-Djava.net.preferIPv4Stack=true -Xms1G -Xmx3G -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=1G'
    ports:
      - 7080:9080
      - 7990:9990
      - 7443:9443
    healthcheck:
      test: 'bash /opt/keycloak/health-check.sh'
      interval: 5s
      timeout: 5s
      retries: 50
      start_period: 10s
    labels:
      org.springframework.boot.ignore: true
    networks:
      - ns-network
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - /data/noosphere/config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '9898:80'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - ns-network
  noosphere-mysql:
    container_name: noosphere-mysql
    user: '0:110'
    image: mysql:9.2.0
    volumes:
      - /data/noosphere/config/mysql:/etc/mysql/conf.d
      - /data/noosphere/config/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - 3356:3306
    command: mysqld --lower_case_table_names=1 --max_connections=1000 --max-allowed-packet=64M --skip-mysqlx --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --collation_server=utf8mb4_general_ci
    healthcheck:
      test: ['CMD-SHELL', 'mysql -e "SHOW DATABASES;" && sleep 5']
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - ns-network
  noosphere-sonar:
    container_name: noosphere-sonar
    image: sonarqube:25.5.0.107428-community
    environment:
      - SONAR_FORCEAUTHENTICATION=false
    ports:
      - 9001:9000
      - 9000:9000
    networks:
      - ns-network
  noosphere-consul:
    container_name: noosphere-consul
    image: hashicorp/consul:1.21.5
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
    command: consul agent -dev -ui -client 0.0.0.0 -log-level=INFO
    labels:
      org.springframework.boot.ignore: true
    networks:
      - ns-network
  noosphere-consul-config-loader:
    container_name: noosphere-consul-config-loader
    image: jhipster/consul-config-loader:v0.4.1
    volumes:
      - /data/noosphere/config/central-server-config:/config
    environment:
      - INIT_SLEEP_SECONDS=5
      - CONSUL_URL=consul
      - CONSUL_PORT=8500
    labels:
      org.springframework.boot.ignore: true
    networks:
      - ns-network
  noosphere-pulsar:
    container_name: noosphere-pulsar
    image: apachepulsar/pulsar:4.0.4
    ports:
      - 9082:8080
      - 6650:6650
    environment:
      PULSAR_MEM: ' -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g'
    command: bin/pulsar standalone
    labels:
      org.springframework.boot.ignore: true
    networks:
      - ns-network
  noosphere-zipkin:
    container_name: noosphere-zipkin
    image: openzipkin/zipkin:3.5.1
    ports:
      - 9411:9411
    networks:
      - ns-network
  noosphere-prometheus:
    container_name: noosphere-prometheus
    image: prom/prometheus:v3.3.1
    volumes:
      - /data/noosphere/config/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - ns-network
  noosphere-grafana:
    container_name: noosphere-grafana
    image: grafana/grafana:12.0.0
    volumes:
      - /data/noosphere/config/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - 3000:3000
    networks:
      - ns-network
  noosphere-swagger-editor:
    container_name: noosphere-swagger-editor
    image: swaggerapi/swagger-editor:latest
    ports:
      - 7742:8080
    networks:
      - ns-network
  noosphere-control-center:
    container_name: noosphere-control-center
    image: 'jhipster/jhipster-control-center:v0.5.0'
    command:
      - /bin/sh
      - -c
      # Patch /etc/hosts to support resolving host.docker.internal to the internal IP address used by the host in all OSes
      - echo "`ip route | grep default | cut -d ' ' -f3` host.docker.internal" | tee -a /etc/hosts > /dev/null && java -jar /jhipster-control-center.jar
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs,none,oauth2
      # For keycloak to work, you need to add '127.0.0.1 keycloak' to your hosts file
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://noosphere-auth:9080/realms/noosphere
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=noosphere-control-center
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=${HPP_AUTH_WEB_APP_SECRET}
      - SPRING_CLOUD_CONSUL_HOST=host.docker.internal
      - SPRING_CLOUD_CONSUL_PORT=8500
      - LOGGING_FILE_NAME=/tmp/noosphere-control-center.log
    ports:
      - 7419:7419
    networks:
      - ns-network
  noosphere-hazelcast-management-center:
    container_name: noosphere-hazelcast-management-center
    image: hazelcast/management-center:5.7.1
    ports:
      - 8180:8080
    networks:
      - ns-network
volumes:
  mysql-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/noosphere/mysql
