# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: noospherehub
services:
  noosphere-anvil:
    container_name: noosphere-anvil
    # This is the official Foundry image which includes anvil, forge, and cast
    image: ghcr.io/foundry-rs/foundry

    # This command starts anvil and binds it to all network interfaces
    # inside the container, which is necessary for port mapping to work.
    command: anvil --host 0.0.0.0

    ports:
      # This maps your local machine's port 8545 to the container's port 8545.
      - '8545:8545'
