name: noospherehub
services:
  noosphere-hub:
    image: ghcr.io/hpp-io/noosphere-hub:test2
    container_name: noosphere-hub
    user: '0:110'
    environment:
      - _JAVA_OPTIONS=-Xmx2048m -Xms1024m -Djava.net.preferIPv4Stack=true -Djavax.net.ssl.trustStore=/app/truststore.p12 -Djavax.net.ssl.trustStorePassword=${HPP_KEYSTORE_PASSWORD} -Dspring.cloud.consul.discovery.hostname=nstest.hpp.io -Dspring.cloud.consul.discovery.prefer-ip-address=false -Dspring.cloud.consul.discovery.scheme=https
      - SPRING_PROFILES_ACTIVE=test2,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:mysql://noosphere-mysql:3306/nshub?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
      - SPRING_LIQUIBASE_URL=jdbc:mysql://noosphere-mysql:3306/nshub?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://authtest.hpp.io/realms/noosphere
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=${HPP_AUTH_WEB_APP_SECRET}
      - SPRING_PULSAR_CLIENT_SERVICE_URL=pulsar://noosphere-pulsar:6650
      - SPRING_PULSAR_ADMINISTRATION_SERVICE_URL=http://noosphere-pulsar:9082
      - SPRING_CLOUD_CONSUL_HOST=noosphere-consul
      - APPLICATION_KEYCLOAK_AUTH_URL=https://authtest.hpp.io
      - APPLICATION_KEYCLOAK_ADMIN_CLIENT_SECRET=${HPP_AUTH_ADMIN_CLI_SECRET}
      - APPLICATION_KEYSTORE_STORE_PASSWORD=${HPP_KEYSTORE_PASSWORD}
      - APPLICATION_KEYSTORE_PATH=/app/hpp-keystore.p12
      - APPLICATION_KEYSTORE_KEYS_ETH=${HPP_ETH_KEY_ALIAS}
      - APPLICATION_BLOCKCHAIN_ROUTER_ADDRESS=${HPP_ROUTER_ADDRESS}
      - HPP_APP_KIT_PROJECT_ID=${HPP_APP_KIT_PROJECT_ID}
      - HPP_ENV=${HPP_ENV}
      - LOGGING_FILE_PATH=/app/logs
    volumes:
      - /data/noosphere/config/hpp-keystore.p12:/app/hpp-keystore.p12
      - /data/noosphere/config/truststore.p12:/app/truststore.p12
      - /data/noosphere/logs/nshub-logs:/app/logs
    ports:
      - 8085:8085
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - https://nstest.hpp.io/management/health
      interval: 5s
      timeout: 5s
      retries: 40
  #    depends_on:
  #      mysql:
  #        condition: service_healthy
  #      keycloak:
  #        condition: service_healthy
