# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: noospherehub
services:
  noosphere-gateway:
    image: ghcr.io/hpp-io/noosphere-gateway:test2
    container_name: noosphere-gateway
    user: '0:124'
    environment:
      - _JAVA_OPTIONS=-Xmx1024m -Xms512m -Djava.net.preferIPv4Stack=true -Djavax.net.ssl.trustStore=/app/truststore.p12 -Djavax.net.ssl.trustStorePassword=${HPP_KEYSTORE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=test2,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=noosphere-consul
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://authtest.hpp.io/realms/noosphere
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=${HPP_AUTH_WEB_APP_SECRET}
      - SPRING_PULSAR_CLIENT_SERVICE_URL=pulsar://noosphere-pulsar:6650
      - SPRING_PULSAR_ADMINISTRATION_SERVICE_URL=http://noosphere-pulsar:9082
      - APPLICATION_KEYCLOAK_AUTH_URL=https://authtest.hpp.io
      - APPLICATION_KEYCLOAK_ADMIN_CLIENT_SECRET=${HPP_AUTH_ADMIN_CLI_SECRET}
      - LOGGING_FILE_PATH=/app/logs
      - HPP_APP_KIT_PROJECT_ID=${HPP_APP_KIT_PROJECT_ID}
    volumes:
      - /data/noosphere/config/truststore.p12:/app/truststore.p12
      - /data/noosphere/logs/ng-logs:/app/logs
    ports:
      - 8280:8280
    extra_hosts:
      - 'host.docker.internal:host-gateway'
