events { worker_connections 1024; }

http {
#     server {
#         listen 80;
#         server_name test.hpp.io; # The hostname you are using
#
#         location / {
#             # Forward to keycloak on its internal docker network name and port
#             # 'keycloak-test' is the service name from docker-compose
#             proxy_pass http://keycloak-test:8080;
#
#             # Set correct headers for Keycloak
#             proxy_headers_hash_max_size 512;
#             proxy_headers_hash_bucket_size 128;
#             proxy_set_header Host $host;
#             proxy_set_header X-Real-IP $remote_addr;
#             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#             proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
#
#             # We will NOT pass X-Forwarded-Proto, as we know Keycloak ignores it.
#
#             # This is the magic:
#             # Find and replace all "http://" links with "https://".
#             sub_filter 'http://test.hpp.io' 'https://test.hpp.io';
#
#             # Make sure it replaces all instances, not just the first.
#             sub_filter_once off;
#         }
#     }
    server {
            listen 80;
            server_name authtest.hpp.io; # The hostname you are using

            location / {
                # Forward to keycloak on its internal docker network name and port
                # 'keycloak-test' is the service name from docker-compose
                proxy_pass http://noosphere-auth:9080;

                # Set correct headers for Keycloak
                proxy_headers_hash_max_size 512;
                proxy_headers_hash_bucket_size 128;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;

                # We will NOT pass X-Forwarded-Proto, as we know Keycloak ignores it.

                # This is the magic:
                # Find and replace all "http://" links with "https://".
                sub_filter 'http://authtest.hpp.io' 'https://authtest.hpp.io';

                # Make sure it replaces all instances, not just the first.
                sub_filter_once off;
            }
        }
    server {
            listen 80;
            server_name ngtest.hpp.io; # The hostname you are using

            location / {
                # Forward to keycloak on its internal docker network name and port
                # 'keycloak-test' is the service name from docker-compose
                proxy_pass http://noosphere-gateway:8280;

                # Set correct headers for Keycloak
                proxy_headers_hash_max_size 512;
                proxy_headers_hash_bucket_size 128;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;

                # We will NOT pass X-Forwarded-Proto, as we know Keycloak ignores it.

                # This is the magic:
                # Find and replace all "http://" links with "https://".
                sub_filter 'http://ngtest.hpp.io' 'https://ngtest.hpp.io';

                # Make sure it replaces all instances, not just the first.
                sub_filter_once off;
            }
        }
}