events { worker_connections 1024; }

http {
    sub_filter 'http://$host' 'https://$host';
    sub_filter_once off;

    server {
            listen 80;
            server_name authtest.hpp.io; # The hostname you are using

            location / {
                # Forward to keycloak on its internal docker network name and port
                # 'keycloak-test' is the service name from docker-compose
                proxy_pass http://noosphere-auth:9080;

                # Set correct headers for Keycloak
                proxy_headers_hash_max_size 512;
                proxy_headers_hash_bucket_size 128;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;

                # We will NOT pass X-Forwarded-Proto, as we know Keycloak ignores it.
            }
        }
    server {
            listen 80;
            server_name ngtest.hpp.io; # The hostname you are using

            location / {
                # Forward to keycloak on its internal docker network name and port
                # 'keycloak-test' is the service name from docker-compose
                proxy_pass http://noosphere-gateway:8280;

                # Set correct headers for Keycloak
                proxy_headers_hash_max_size 512;
                proxy_headers_hash_bucket_size 128;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;

                # We will NOT pass X-Forwarded-Proto, as we know Keycloak ignores it.
            }
        }
}