hazelcast:
  instance-name: noosphere-hub
  network:
    port:
      port: 5701
      port-count: 100
      auto-increment: true
    join:
      multicast:
        enabled: false
      tcp-ip: # For Kubernetes, we use DNS lookup
        enabled: true # Set to false if using Kubernetes discovery
        member-list:
          - noosphere-hub
