package io.hpp.noosphere.hub.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AgentContainerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgentContainerAllPropertiesEquals(AgentContainer expected, AgentContainer actual) {
        assertAgentContainerAutoGeneratedPropertiesEquals(expected, actual);
        assertAgentContainerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgentContainerAllUpdatablePropertiesEquals(AgentContainer expected, AgentContainer actual) {
        assertAgentContainerUpdatableFieldsEquals(expected, actual);
        assertAgentContainerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgentContainerAutoGeneratedPropertiesEquals(AgentContainer expected, AgentContainer actual) {
        assertThat(actual)
            .as("Verify AgentContainer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgentContainerUpdatableFieldsEquals(AgentContainer expected, AgentContainer actual) {
        assertThat(actual)
            .as("Verify AgentContainer relevant properties")
            .satisfies(a -> assertThat(a.getStatusCode()).as("check statusCode").isEqualTo(expected.getStatusCode()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgentContainerUpdatableRelationshipsEquals(AgentContainer expected, AgentContainer actual) {
        assertThat(actual)
            .as("Verify AgentContainer relationships")
            .satisfies(a -> assertThat(a.getNode()).as("check node").isEqualTo(expected.getNode()))
            .satisfies(a -> assertThat(a.getContainer()).as("check container").isEqualTo(expected.getContainer()));
    }
}
