# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: noospherehub
services:
  app:
    image: noospherehub
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=noosphere-consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:noosphere-mysql://mysql:3306/nshub?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
      - SPRING_LIQUIBASE_URL=jdbc:noosphere-mysql://mysql:3306/nshub?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://noosphere-auth:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
      - SPRING_PULSAR_CLIENT_SERVICE_URL=pulsar://noosphere-pulsar:6650
      - SPRING_PULSAR_ADMINISTRATION_SERVICE_URL=http://noosphere-pulsar:8080
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8085/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      noosphere-mysql:
        condition: service_healthy
      noosphere-auth:
        condition: service_healthy
  noosphere-mysql:
    extends:
      file: ./mysql.yml
      service: noosphere-mysql
  noosphere-auth:
    extends:
      file: ./keycloak.yml
      service: noosphere-auth
  noosphere-pulsar:
    extends:
      file: ./pulsar.yml
      service: noosphere-pulsar
  noosphere-consul:
    extends:
      file: ./consul.yml
      service: noosphere-consul
  noosphere-consul-config-loader:
    extends:
      file: ./consul.yml
      service: noosphere-consul-config-loader
