# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: noospherehub
services:
  noosphere-auth:
    container_name: noosphere-auth
    image: jungsoo827/noosphere-auth:demo
    command: 'start-dev --import-realm'
    volumes:
      - ./realm-config:/opt/keycloak/data/import
      - ./realm-config/keycloak-health-check.sh:/opt/keycloak/health-check.sh
    environment:
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://noosphere-mysql:3306/keycloak
      - KC_DB_USERNAME=nsuser
      - KC_DB_PASSWORD=nshub2025!1
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=nshub2025!1
      - KC_FEATURES=scripts
      - KC_HTTP_PORT=7080
      - KC_HTTPS_PORT=7443
      - KC_HEALTH_ENABLED=true
      - KC_HTTP_MANAGEMENT_PORT=7990
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - JDBC_PARAMS='useUnicode=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true'
      - PROXY_ADDRESS_FORWARDING=true
      - JAVA_OPTS='-Djava.net.preferIPv4Stack=true -Xms1G -Xmx3G -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=1G'
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 0.0.0.0:7080:7080
      - 0.0.0.0:7443:7443
      - 0.0.0.0:7990:7990
    healthcheck:
      test: 'bash /opt/keycloak/health-check.sh'
      interval: 5s
      timeout: 5s
      # Increased retries due to slow Keycloak startup in GitHub Actions using MacOS
      retries: 50
      start_period: 10s
    labels:
      org.springframework.boot.ignore: true
