# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: noospherehub
services:
  noosphere-swagger-editor:
    image: swaggerapi/swagger-editor:latest
    ports:
      - 0.0.0.0:7742:8080
