# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: noospherehub
services:
  noosphere-zipkin:
    container_name: noosphere-zipkin
    image: openzipkin/zipkin:3.5.1
    ports:
      - 9411:9411
